MaxProcess: 0
TimeZone: "+08:00"
EnableI18n: true
ExcelDir: assets/xls/
ProtoImportPath: ""
LogLevel: ERROR

Outs:
  Client:
    ProtoPath: assets/out_proto/client/
    PbPath:    assets/out_pb/client/
    DataPath:  assets/out_data/client/
    DataExt:  ".bytes"
    PackageName:  "pb"
    CodeLanguage:  "csharp"
  Server:
    ProtoPath: assets/out_proto/server/
    PbPath: assets/out_pb/server/
    DataPath: assets/out_data/server/
    DataExt: ".data"
    PackageName: "pbs"
    GoPackagePath: "server/pbs"
    GoModulePath: "server"
    CodeLanguage: "golang"

TplCodePaths:
  golang: assets/template/golang/
  csharp: assets/template/csharp/
  godot: assets/template/godot/
  cpp: assets/template/cpp/
  java: assets/template/java/

CodeOutPaths:
  golang: assets/out_code/golang/
  csharp: assets/out_code/csharp/
  godot: assets/out_code/godot/
  cpp:    assets/out_code/cpp/
  java:   assets/out_code/java/
