ExcelDir: assets/xls/

ProtoImportPath: ""

Outs:
  Client:
    ProtoPath: assets/out_proto/client/
    PbPath:    assets/out_pb/client/
    DataPath:  assets/out_data/client/
    DataExt:  ".bytes"
    PackageName:  "pb"
    CodeLanguage:  "csharp"
  Server:
    ProtoPath: assets/out_proto/server/
    PbPath: assets/out_pb/server/
    DataPath: assets/out_data/server/
    DataExt: ".data"
    PackageName: "pbs"
    CodeLanguage: "golang"

TplCodePaths:
  golang: assets/out_code/golang/
  csharp: assets/out_code/csharp/
  cpp:    assets/out_code/cpp/
  java:   assets/out_code/java/

CodeOutPaths:
  golang: assets/template/golang/
  csharp: assets/template/csharp/
  cpp:    assets/template/cpp/
  java:   assets/template/java/
